// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

/**
 * Represents an API key info (without the actual key)
 */
export const zApiKeyInfo = z.object({
  created_at: z.string().datetime(),
  id: z.string().uuid(),
  is_active: z.boolean(),
  key_prefix: z.string(),
  name: z.string(),
});

export const zBot = z.object({
  id: z.string(),
  name: z.string(),
});

export const zContent = z.object({
  content_id: z.string(),
  url: z.string(),
});

export const zMessage = z.object({
  attached_media: z.union([zContent, z.null()]).optional(),
  from_bot: z.boolean(),
  id: z.union([z.string(), z.null()]).optional(),
  sent_at: z.union([z.coerce.bigint(), z.null()]).optional(),
  text: z.string(),
});

export const zConversation = z.object({
  bot_id: z.string(),
  id: z.string(),
  messages: z.array(zMessage),
  user_id: z.union([z.string(), z.null()]).optional(),
});

export const zSearchedMessage = z.object({
  from_bot: z.boolean(),
  match_end: z.number().int().gte(0),
  match_start: z.number().int().gte(0),
  message_text: z.string(),
  sent_at: z.coerce.bigint(),
});

export const zConversationHeader = z.object({
  bot_id: z.string(),
  id: z.string(),
  last_message: z.union([zMessage, z.null()]).optional(),
  message_count: z.number().int().gte(0),
  searched_message: z.union([zSearchedMessage, z.null()]).optional(),
  user_id: z.string(),
});

export const zCreateApiKeyRequest = z.object({
  name: z.string(),
});

export const zCreateApiKeyResponse = z.object({
  api_key: z.string(),
  key_info: zApiKeyInfo,
});

export const zCreateBotRequest = z.object({
  name: z.string(),
});

export const zCreateBotResponse = z.object({
  bot: zBot,
});

export const zCreateConversationRequest = z.object({
  bot_id: z.string(),
  create_user_if_not_exists: z.union([z.boolean(), z.null()]).optional(),
  user_id: z.string(),
  with_messages: z.union([z.array(zMessage), z.null()]).optional(),
});

export const zCreateConversationResponse = z.object({
  conversation: zConversation,
});

export const zDeactivateApiKeyResponse = z.object({
  message: z.string(),
});

export const zGetBotResponse = z.object({
  bot: zBot,
});

export const zGetConversationResponse = z.object({
  bot_id: z.string(),
  messages: z.array(zMessage),
  user_id: z.string(),
});

export const zMemoryResponse = z.object({
  text: z.string(),
});

export const zGetMemoriesResponse = z.object({
  bot_memories: z.array(zMemoryResponse),
  user_memories: z.array(zMemoryResponse),
});

export const zListApiKeysResponse = z.object({
  api_keys: z.array(zApiKeyInfo),
});

export const zListBotsResponse = z.object({
  bots: z.array(zBot),
});

export const zListConversationsResponse = z.object({
  conversations: z.array(zConversationHeader),
});

export const zSendMessageRequest = z.object({
  message: zMessage,
});

export const zUpdateBotRequest = z.object({
  name: z.string(),
});

export const zUpdateBotResponse = z.object({
  bot: zBot,
});

export const zListApiKeysData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * API keys retrieved successfully
 */
export const zListApiKeysResponse2 = zListApiKeysResponse;

export const zCreateApiKeyData = z.object({
  body: zCreateApiKeyRequest,
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * API key created successfully
 */
export const zCreateApiKeyResponse2 = zCreateApiKeyResponse;

export const zDeactivateApiKeyData = z.object({
  body: z.never().optional(),
  path: z.object({
    key_id: z.string(),
  }),
  query: z.never().optional(),
});

/**
 * API key deactivated successfully
 */
export const zDeactivateApiKeyResponse2 = zDeactivateApiKeyResponse;

export const zListBotsData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Bots retrieved successfully
 */
export const zListBotsResponse2 = zListBotsResponse;

export const zCreateBotData = z.object({
  body: zCreateBotRequest,
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Bot created successfully
 */
export const zCreateBotResponse2 = zCreateBotResponse;

export const zDeleteBotData = z.object({
  body: z.never().optional(),
  path: z.object({
    bot_id: z.string().uuid(),
  }),
  query: z.never().optional(),
});

/**
 * Bot deleted successfully
 */
export const zDeleteBotResponse = z.void();

export const zGetBotData = z.object({
  body: z.never().optional(),
  path: z.object({
    bot_id: z.string().uuid(),
  }),
  query: z.never().optional(),
});

/**
 * Bot retrieved successfully
 */
export const zGetBotResponse2 = zGetBotResponse;

export const zUpdateBotData = z.object({
  body: zUpdateBotRequest,
  path: z.object({
    bot_id: z.string().uuid(),
  }),
  query: z.never().optional(),
});

/**
 * Bot updated successfully
 */
export const zUpdateBotResponse2 = zUpdateBotResponse;

export const zListConversationsData = z.object({
  body: z.never().optional(),
  path: z.never().optional(),
  query: z
    .object({
      bot_id: z.union([z.string(), z.null()]).optional(),
      user_id: z.union([z.string(), z.null()]).optional(),
      conversation_id: z.union([z.string(), z.null()]).optional(),
      min_messages: z.union([z.number().int(), z.null()]).optional(),
      max_messages: z.union([z.number().int(), z.null()]).optional(),
      message_content: z.union([z.string(), z.null()]).optional(),
      min_last_message_date: z.union([z.number().int(), z.null()]).optional(),
      max_last_message_date: z.union([z.number().int(), z.null()]).optional(),
    })
    .optional(),
});

/**
 * Conversations retrieved successfully
 */
export const zListConversationsResponse2 = zListConversationsResponse;

export const zCreateConversationData = z.object({
  body: zCreateConversationRequest,
  path: z.never().optional(),
  query: z.never().optional(),
});

/**
 * Conversation created successfully
 */
export const zCreateConversationResponse2 = zCreateConversationResponse;

export const zGetConversationData = z.object({
  body: z.never().optional(),
  path: z.object({
    id: z.string(),
  }),
  query: z.never().optional(),
});

/**
 * Conversation retrieved successfully
 */
export const zGetConversationResponse2 = zGetConversationResponse;

export const zGetMemoriesData = z.object({
  body: z.never().optional(),
  path: z.object({
    id: z.string(),
  }),
  query: z.never().optional(),
});

/**
 * Memories retrieved successfully
 */
export const zGetMemoriesResponse2 = zGetMemoriesResponse;

export const zSendMessageData = z.object({
  body: zSendMessageRequest,
  path: z.object({
    id: z.string(),
  }),
  query: z.never().optional(),
});
